sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.sourceEncoding=UTF-8

# Sumber & test
sonar.sources=.
sonar.tests=tests
sonar.exclusions=coverage/**,k6/**

# Coverage (dari Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# (opsional) Sesuaikan jika pakai monorepo:
# sonar.working.directory=.sonar
sonar.organization=ajied21
sonar.host.url=https://sonarcloud.io

